# Generated by Django 5.1.1 on 2024-09-10 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_comment_delete_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['comment_date']},
        ),
    ]
